name: Ejecutar pruebas automatizadas

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    environment: pr

    permissions:
      contents: read
      security-events: write  # Permiso necesario para Dependency Graph

    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'

      - name: Instalar dependencias con Maven
        run: mvn clean install -DskipTests

      - name: Compilar código Java
        run: mvn compile

      - name: Ejecutar todas las pruebas en orden
        run: mvn test -Dtest=orangeHrm.runners.RunnerCamposVacios,orangeHrm.runners.RunnerLogFallido,orangeHrm.runners.RunnerLoginExit,orangeHrm.runners.RunnerUserVacio

      - name: Subir dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4

      - name: Publicar resultados de pruebas
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports
